apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p2p
  namespace: argocd
spec:
  project: p2p

  source:
    repoURL: https://github.com/redmictian/p2p-devops-test.git
    targetRevision: HEAD
    path: apps/p2p/chart
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: qa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      # Ovverride any manual changes by auto sync
      selfHeal: true
      # yaml is deleted or renamed results in the same outcome in k8s
      prune: true