apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.env }}-{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
      - name: "{{ .Values.env }}-{{ .Release.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: {{ .Values.container.portName }}
          containerPort: {{ .Values.container.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}